# Skipgram Classification Naive bayes

## Preprocessing

### Case Folding
Tahap ini dilakukan untuk menyeragamkan teks dengan mengubah seluruh huruf menjadi huruf kecil (lowercase). Proses ini bertujuan agar kata yang sama tidak dianggap berbeda hanya karena penggunaan huruf besar dan huruf kecil, misalnya kata “Belajar”, “BELAJAR”, dan “belajar” diubah menjadi “belajar”.

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

file_path = r"dataset_detik_sport_finance.xlsx"
df = pd.read_excel(file_path)

df["teks_lower"] = df["isi_berita"].str.lower()

df[["isi_berita", "teks_lower"]].head()

,isi_berita,teks_lower
0,"Pegokar muda Indonesia, Morgan Holindo, tak pu...","pegokar muda indonesia, morgan holindo, tak pu..."
1,Pacuan kuda Indonesia mulai diarahkan menuju p...,pacuan kuda indonesia mulai diarahkan menuju p...
2,"Jelang Asian Games 2026, dukungan untuk 432 at...","jelang asian games 2026, dukungan untuk 432 at..."
3,Pupus sudah harapan Sean Gelael dan rekan-reka...,pupus sudah harapan sean gelael dan rekan-reka...
4,Barra Ghaisan Zeinatma menunjukkan perkembanga...,barra ghaisan zeinatma menunjukkan perkembanga...

### Cleaning
Tahap cleaning dilakukan untuk membersihkan teks dari unsur-unsur yang tidak diperlukan dalam proses pengolahan data. Pada tahap ini, teks diubah menjadi tipe data string, kemudian pola  kata author  biasanya di akhir berita yang tidak diperlukan, angka, tanda baca, dan karakter selain huruf serta spasi dihapus. Selanjutnya, spasi berlebih dihilangkan agar teks menjadi lebih rapi dan mudah diproses pada tahap text preprocessing berikutnya.

In [5]:
import string
import re

def cleaning(text):
    text = str(text)
    # pola nama author didalam kurung
    text = re.sub(
        r'\([a-z]{2,5}/[a-z]{2,5}\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )
    
    # Hapus tanda baca
    text = text.translate(str.maketrans("", "", string.punctuation))
    
    # Hapus karakter selain huruf dan spasi
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    
    # Hapus spasi berlebih
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df["teks_clean"] = df["teks_lower"].apply(cleaning)

df[["teks_lower", "teks_clean"]].head()

,teks_lower,teks_clean
0,"pegokar muda indonesia, morgan holindo, tak pu...",pegokar muda indonesia morgan holindo tak puas...
1,pacuan kuda indonesia mulai diarahkan menuju p...,pacuan kuda indonesia mulai diarahkan menuju p...
2,"jelang asian games 2026, dukungan untuk 432 at...",jelang asian games dukungan untuk atlet indone...
3,pupus sudah harapan sean gelael dan rekan-reka...,pupus sudah harapan sean gelael dan rekanrekan...
4,barra ghaisan zeinatma menunjukkan perkembanga...,barra ghaisan zeinatma menunjukkan perkembanga...

### Tokenisasi
Tahap tokenization dilakukan untuk memecah teks menjadi bagian-bagian yang lebih kecil berupa kata atau token. Pada kode ini, fungsi split() digunakan untuk memisahkan teks berdasarkan spasi sehingga setiap kata disimpan dalam bentuk elemen pada sebuah list. Hasil tokenisasi disimpan dalam kolom baru bernama tokens.

In [6]:
df["tokens"] = df["teks_clean"].apply(lambda x: x.split())

df[["teks_clean", "tokens"]].head()

,teks_clean,tokens
0,pegokar muda indonesia morgan holindo tak puas...,"[pegokar, muda, indonesia, morgan, holindo, ta..."
1,pacuan kuda indonesia mulai diarahkan menuju p...,"[pacuan, kuda, indonesia, mulai, diarahkan, me..."
2,jelang asian games dukungan untuk atlet indone...,"[jelang, asian, games, dukungan, untuk, atlet,..."
3,pupus sudah harapan sean gelael dan rekanrekan...,"[pupus, sudah, harapan, sean, gelael, dan, rek..."
4,barra ghaisan zeinatma menunjukkan perkembanga...,"[barra, ghaisan, zeinatma, menunjukkan, perkem..."

### Stopword Removal
Tahap stopword removal dilakukan untuk menghapus kata-kata umum yang kurang memberikan informasi penting dalam proses analisis teks. Pada tahap ini, pustaka Sastrawi digunakan untuk memperoleh daftar stopword dalam bahasa Indonesia. Selanjutnya, setiap kata dalam hasil tokenisasi diperiksa dan kata yang terdapat dalam daftar stopword akan dihapus. Kata-kata yang tidak termasuk dalam daftar tersebut dipertahankan, kemudian hasilnya disimpan dalam kolom baru bernama tokens_no_stopword.

In [7]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stopwords]

df["tokens_no_stopword"] = df["tokens"].apply(remove_stopwords)

df[["tokens", "tokens_no_stopword"]].head()

,tokens,tokens_no_stopword
0,"[pegokar, muda, indonesia, morgan, holindo, ta...","[pegokar, muda, indonesia, morgan, holindo, ta..."
1,"[pacuan, kuda, indonesia, mulai, diarahkan, me...","[pacuan, kuda, indonesia, mulai, diarahkan, me..."
2,"[jelang, asian, games, dukungan, untuk, atlet,...","[jelang, asian, games, dukungan, atlet, indone..."
3,"[pupus, sudah, harapan, sean, gelael, dan, rek...","[pupus, harapan, sean, gelael, rekanrekannya, ..."
4,"[barra, ghaisan, zeinatma, menunjukkan, perkem...","[barra, ghaisan, zeinatma, menunjukkan, perkem..."

### Stemming
Tahap stemming dilakukan untuk mengubah kata berimbuhan menjadi kata dasarnya menggunakan pustaka Sastrawi. Pada tahap ini, objek stemmer dibuat melalui StemmerFactory(), kemudian fungsi stemming() diterapkan pada setiap kata dalam kolom tokens_no_stopword. Setiap kata diproses menggunakan metode stem() untuk memperoleh bentuk dasarnya. Hasil proses tersebut disimpan dalam kolom baru bernama tokens_stem agar dapat dibandingkan dengan kata-kata sebelum proses stemming.

In [8]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df["tokens_stem"] = df["tokens_no_stopword"].apply(stemming)

df[["tokens_no_stopword", "tokens_stem"]].head()

df["teks_preprocessed"] = df["tokens_stem"].apply(
    lambda x: " ".join(x)
)

df[["isi_berita", "teks_preprocessed", "jenis_berita"]].head()

,isi_berita,teks_preprocessed,jenis_berita
0,"Pegokar muda Indonesia, Morgan Holindo, tak pu...",gokar muda indonesia morgan holindo tak puas c...,sport
1,Pacuan kuda Indonesia mulai diarahkan menuju p...,pacu kuda indonesia mulai arah tuju panggung d...,sport
2,"Jelang Asian Games 2026, dukungan untuk 432 at...",jelang asi games dukung atlet indonesia terus ...,sport
3,Pupus sudah harapan Sean Gelael dan rekan-reka...,pupus harap sean gelael rekanrekannya team wrt...,sport
4,Barra Ghaisan Zeinatma menunjukkan perkembanga...,barra ghaisan zeinatma tunjuk kembang positif ...,sport

## Menyiapkan 2 Skenario Data (Tanpa vs Dengan Stopword Removal)

Dua skenario yang akan dibandingkan:

1. **Tanpa stopword removal** &rarr; menggunakan `tokens` (hasil tokenisasi) yang langsung di-*stem*.
2. **Dengan stopword removal** &rarr; menggunakan `tokens_no_stopword` yang sudah di-*stem* (`tokens_stem` / `teks_preprocessed`, sudah dibuat di bagian Stemming di atas).

In [ ]:
# Skenario 1: TANPA stopword removal -> stemming langsung dari token hasil tokenisasi

df["tokens_stem_full"] = df["tokens"].apply(stemming)
df["teks_preprocessed_full"] = df["tokens_stem_full"].apply(lambda x: " ".join(x))

# Skenario 2: DENGAN stopword removal -> sudah tersedia di df["tokens_stem"] / df["teks_preprocessed"]

skenario = {
    "tanpa_stopword_removal": df["tokens_stem_full"],
    "dengan_stopword_removal": df["tokens_stem"],
}

df[["tokens_stem_full", "tokens_stem"]].head()

,tokens_stem_full,tokens_stem
0,"[gokar, muda, indonesia, morgan, holindo, tak,...","[gokar, muda, indonesia, morgan, holindo, tak,..."
1,"[pacu, kuda, indonesia, mulai, arah, tuju, pan...","[pacu, kuda, indonesia, mulai, arah, tuju, pan..."
2,"[jelang, asi, games, dukung, untuk, atlet, ind...","[jelang, asi, games, dukung, atlet, indonesia,..."
3,"[pupus, sudah, harap, sean, gelael, dan, rekan...","[pupus, harap, sean, gelael, rekanrekannya, te..."
4,"[barra, ghaisan, zeinatma, tunjuk, kembang, po...","[barra, ghaisan, zeinatma, tunjuk, kembang, po..."

## Word Embedding Skipgram
Word embedding yang digunakan yaitu model Word2Vec dengan metode Skip-Gram pada setiap skenario data token menggunakan parameter ukuran vektor 100, window 5, dan 100 epochs. Model yang dihasilkan disimpan dalam skipgram_models.

In [10]:
# %pip install gensim

In [ ]:
from gensim.models import Word2Vec
import pandas as pd
import numpy as np


# FUNGSI TRAINING SKIP-GRAM
def train_skipgram(
    corpus_tokens,
    vector_size=100,
    window=5,
    min_count=1,
    epochs=100,
    seed=42
):
    
    model = Word2Vec(
        sentences=corpus_tokens.tolist(),
        vector_size=vector_size,
        window=window,
        min_count=min_count,
        sg=1,          # Skip-Gram
        epochs=epochs,
        seed=seed,
        workers=1333
    )
    
    return model


# 2. TRAIN SKIP-GRAM
skipgram_models = {}

for nama, tokens_col in skenario.items():

    print("=" * 80)
    print(f"SKENARIO: {nama}")
    print("=" * 80)

    model = train_skipgram(
        corpus_tokens=tokens_col,
        vector_size=100,
        window=5
    )

    skipgram_models[nama] = model

    print("Jumlah vocabulary :", len(model.wv))
    print("Vector size       :", model.vector_size)
    print("Window             :", model.window)
    print("Ukuran matrix      :", model.wv.vectors.shape)
    print()


# TABEL VECTOR SPACE
hasil_vector_space = []

for nama, model in skipgram_models.items():

    # Jumlah vocabulary
    vocab_size = len(model.wv)

    # Embedding matrix
    embedding_matrix = model.wv.vectors

    # Ukuran matrix
    rows, cols = embedding_matrix.shape

    hasil_vector_space.append({
        "Skenario": nama,

        "Vocabulary": vocab_size,

        "Vector Size": model.vector_size,

        "Window": model.window,

        # Sebelum Skip-Gram
        # One-hot secara konseptual
        "Vector Space Sebelum":
            f"{vocab_size} × {vocab_size}",

        "Jumlah Elemen Sebelum":
            vocab_size * vocab_size,

        # Sesudah Skip-Gram
        "Vector Space Sesudah":
            f"{rows} × {cols}",

        "Jumlah Elemen Sesudah":
            rows * cols
    })


df_vector_space = pd.DataFrame(hasil_vector_space)

print("=" * 100)
print("VECTOR SPACE SEBELUM DAN SESUDAH SKIP-GRAM")
print("=" * 100)

display(df_vector_space)

================================================================================
SKENARIO: tanpa_stopword_removal
================================================================================
Jumlah vocabulary : 5346
Vector size       : 100
Window             : 5
Ukuran matrix      : (5346, 100)

================================================================================
SKENARIO: dengan_stopword_removal
================================================================================
Jumlah vocabulary : 5299
Vector size       : 100
Window             : 5
Ukuran matrix      : (5299, 100)

====================================================================================================
VECTOR SPACE SEBELUM DAN SESUDAH SKIP-GRAM
====================================================================================================

,Skenario,Vocabulary,Vector Size,Window,Vector Space Sebelum,Jumlah Elemen Sebelum,Vector Space Sesudah,Jumlah Elemen Sesudah
0,tanpa_stopword_removal,5346,100,5,5346 × 5346,28579716,5346 × 100,534600
1,dengan_stopword_removal,5299,100,5,5299 × 5299,28079401,5299 × 100,529900

In [ ]:
# MENAMPILKAN SELURUH VECTOR HASIL SKIP-GRAM

embedding_tables = {}

for nama, model in skipgram_models.items():

    words = model.wv.index_to_key
    vectors = model.wv.vectors

    df_embedding = pd.DataFrame(
        vectors,
        index=words
    )

    df_embedding.index.name = "word"

    df_embedding.columns = [
        f"dim_{i+1}"
        for i in range(model.vector_size)
    ]

    embedding_tables[nama] = df_embedding

    print("=" * 100)
    print(f"EMBEDDING MATRIX: {nama}")
    print("=" * 100)

    print("Vocabulary    :", len(words))
    print("Vector size   :", model.vector_size)
    print("Ukuran matrix :", vectors.shape)
    print("Jumlah elemen :", vectors.size)

    display(df_embedding)

====================================================================================================
EMBEDDING MATRIX: tanpa_stopword_removal
====================================================================================================
Vocabulary    : 5346
Vector size   : 100
Ukuran matrix : (5346, 100)
Jumlah elemen : 534600

,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,dim_9,dim_10,...,dim_91,dim_92,dim_93,dim_94,dim_95,dim_96,dim_97,dim_98,dim_99,dim_100
word,,,,,,,,,,,,,,,,,,,,,
yang,-0.034173,0.082420,0.021765,0.103697,-0.188211,0.121578,-0.191170,-0.137679,-0.111790,-0.270961,...,-0.130506,-0.052138,0.006378,-0.184934,0.203608,0.073181,0.145668,0.078100,-0.130243,-0.068275
dan,-0.025275,-0.126174,-0.064563,-0.118979,0.022821,0.125066,-0.032093,-0.261027,-0.192725,-0.132759,...,0.016131,-0.032345,0.034789,-0.357205,0.109151,0.081032,-0.044685,0.025605,-0.244525,0.146425
di,0.087175,0.077157,-0.172234,-0.009065,-0.092202,-0.132643,-0.034115,-0.086286,-0.001350,0.197562,...,-0.022061,0.043069,0.131747,-0.136706,-0.000064,0.183995,0.062186,0.133086,-0.418432,0.038648
ini,0.123500,0.107813,-0.349320,0.214954,0.009861,-0.164305,-0.236658,-0.067152,-0.145204,-0.404469,...,-0.085448,-0.084213,-0.001169,0.094034,-0.001877,0.217223,0.157363,-0.113909,-0.225490,-0.292824
untuk,0.105897,0.169904,-0.092634,0.122439,0.065730,0.171047,0.010241,-0.230487,-0.304167,-0.245507,...,-0.342435,-0.101867,-0.179678,0.113716,0.005500,0.267279,0.088268,0.285140,-0.321475,0.008987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
lintang,-0.590434,0.095957,-0.625341,0.154367,0.070287,0.386852,0.481695,-0.070292,-0.071968,-0.222109,...,-0.166358,0.154764,-0.215061,-0.484580,0.011824,-0.004888,-0.464149,0.410420,-0.290311,-0.518373
aral,-0.489480,0.115379,-0.640076,0.226962,0.146655,0.415293,0.439105,-0.082460,0.004264,-0.261590,...,-0.182634,0.064241,-0.282137,-0.506986,0.007421,-0.061803,-0.544795,0.428589,-0.321685,-0.494156
ngegas,-0.090357,-0.282564,-0.453019,0.010199,-0.049430,-0.026627,0.463575,-0.323773,-0.494804,0.396273,...,-0.648299,0.198174,0.168216,-0.096953,-0.140468,-0.018616,-0.255621,-0.115107,-0.461024,-0.168407
prefinal,-0.317302,-0.245192,-0.426976,0.022255,-0.281263,-0.091333,0.603038,0.017046,-0.346922,0.489262,...,-0.637968,-0.033861,0.156239,-0.027511,-0.004444,-0.055165,-0.368423,-0.035915,-0.425211,-0.040027
nasib,0.164873,-0.436794,-0.154410,0.561930,-0.110546,-0.116868,0.537497,-0.569837,-0.424277,-0.349967,...,-0.192745,0.131930,0.100686,-0.380392,-0.156530,-0.367654,-0.172994,-0.016881,-0.853205,-0.473647

====================================================================================================
EMBEDDING MATRIX: dengan_stopword_removal
====================================================================================================
Vocabulary    : 5299
Vector size   : 100
Ukuran matrix : (5299, 100)
Jumlah elemen : 529900

,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,dim_9,dim_10,...,dim_91,dim_92,dim_93,dim_94,dim_95,dim_96,dim_97,dim_98,dim_99,dim_100
word,,,,,,,,,,,,,,,,,,,,,
jadi,-0.174394,0.138641,0.133818,0.004065,0.019979,0.053633,-0.193085,0.364049,-0.577429,-0.029282,...,-0.285192,-0.088064,0.231766,-0.115150,0.285602,-0.313876,-0.238218,-0.230589,-0.141860,-0.179270
indonesia,0.579131,0.053091,-0.041470,-0.266268,0.195195,0.219628,-0.257502,0.200612,-0.402130,0.002994,...,-0.067481,-0.539608,0.345963,-0.317178,0.343709,-0.102155,-0.451377,-0.514628,-0.328086,-0.010510
sebut,-0.103970,-0.063027,0.278865,0.124591,0.107035,0.155094,-0.167267,0.045107,-0.367251,-0.286980,...,-0.169407,-0.283271,0.104836,-0.184840,0.006304,-0.469388,-0.179697,0.011486,-0.165499,-0.257613
laku,-0.006294,-0.094822,-0.301580,-0.049422,-0.184400,-0.163556,-0.167034,0.285982,-0.575041,-0.516558,...,-0.273336,-0.101314,0.322291,-0.188113,-0.242301,0.253829,-0.837237,0.349707,0.181488,-0.457451
kata,0.379777,0.282760,0.303319,0.374245,0.038390,0.334954,-0.577105,0.264310,-0.646194,-0.524326,...,-0.068188,0.094524,0.486265,0.453414,-0.151932,0.000930,-0.209257,-0.008360,-0.033925,-0.505250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
lintang,-0.126351,0.343084,-0.233032,0.529119,-0.308996,-0.125608,-0.456126,0.484340,-0.055937,0.158136,...,-0.651367,-0.231422,0.345581,0.002353,0.188260,0.321837,-0.277070,-0.069388,-0.248567,0.588995
aral,-0.171614,0.487093,-0.248438,0.568372,-0.359485,-0.116112,-0.384959,0.360129,0.022889,0.304388,...,-0.623061,-0.253582,0.378194,0.128706,0.066314,0.309848,-0.127924,-0.119577,-0.348068,0.582689
ngegas,-0.105202,0.853070,0.072631,0.241442,-0.075010,0.029923,-0.016018,-0.009644,0.196648,-0.287434,...,-0.414995,-0.210752,0.396214,0.155970,0.711378,0.252356,-0.135245,0.249932,-0.010966,0.042117
prefinal,-0.101483,0.692239,0.065336,0.217612,-0.054906,0.005152,0.068057,-0.029734,0.256627,-0.318099,...,-0.444272,-0.237858,0.383786,0.330172,0.637346,0.361212,0.162358,0.137584,0.217706,0.163108
nasib,0.156119,0.395998,-0.179411,0.157277,0.034183,-0.002177,0.033857,0.501920,0.416662,-0.096440,...,-0.503775,-0.026247,0.305842,-0.205488,0.473523,-0.095986,-0.433222,0.357679,0.217277,0.071092

## Representasi Dokumen (Rata-rata Vektor Kata)

In [13]:
import numpy as np

def document_vector(model, tokens):
    """Rata-rata vektor kata dalam satu dokumen. Kata di luar vocab diabaikan."""
    vectors = [model.wv[w] for w in tokens if w in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

def build_feature_matrix(model, tokens_series):
    return np.vstack([document_vector(model, toks) for toks in tokens_series])

X_no_sw   = build_feature_matrix(skipgram_models["tanpa_stopword_removal"], skenario["tanpa_stopword_removal"])
X_with_sw = build_feature_matrix(skipgram_models["dengan_stopword_removal"], skenario["dengan_stopword_removal"])

y = df["jenis_berita"]

print("Shape fitur (tanpa stopword removal) :", X_no_sw.shape)
print("Shape fitur (dengan stopword removal):", X_with_sw.shape)

Shape fitur (tanpa stopword removal) : (200, 100)
Shape fitur (dengan stopword removal): (200, 100)

## Klasifikasi Naive Bayes

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

def evaluate_naive_bayes(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )
    clf = GaussianNB()
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, zero_division=0)
    return acc, report, clf

hasil = {}
for nama, X in [("tanpa_stopword_removal", X_no_sw), ("dengan_stopword_removal", X_with_sw)]:
    acc, report, clf = evaluate_naive_bayes(X, y)
    hasil[nama] = {"akurasi": acc, "report": report, "model": clf}
    print(f"=== Skenario: {nama} ===")
    print(f"Akurasi: {acc:.4f}")
    print(report)
    print()

=== Skenario: tanpa_stopword_removal ===
Akurasi: 0.9750
              precision    recall  f1-score   support

     finance       0.95      1.00      0.98        20
       sport       1.00      0.95      0.97        20

    accuracy                           0.97        40
   macro avg       0.98      0.97      0.97        40
weighted avg       0.98      0.97      0.97        40


=== Skenario: dengan_stopword_removal ===
Akurasi: 0.9750
              precision    recall  f1-score   support

     finance       0.95      1.00      0.98        20
       sport       1.00      0.95      0.97        20

    accuracy                           0.97        40
   macro avg       0.98      0.97      0.97        40
weighted avg       0.98      0.97      0.97        40

## Eksperimen: Pengaruh Window Size & Vector Size terhadap Akurasi

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report


# KONFIGURASI EKSPERIMEN

window_list = [5]

# 100, 99, 98, ..., 89
vector_size_list = list(range(100, 88, -1))

eksperimen_hasil = []

best_accuracy = -1

best_skipgram = None
best_clf = None

best_skenario = None
best_window = None
best_vector_size = None

best_precision = None
best_recall = None

best_vocabulary = None
best_embedding_rows = None
best_embedding_cols = None

best_vsm_rows = None
best_vsm_cols = None

for nama_skenario, tokens_col in skenario.items():

    for window in window_list:

        for vector_size in vector_size_list:

            print("\n" + "=" * 70)

            print(f"Skenario    : {nama_skenario}")
            print(f"Window      : {window}")
            print(f"Vector Size : {vector_size}")

            print("=" * 70)

            model = train_skipgram(
                tokens_col,
                vector_size=vector_size,
                window=window
            )

            vocabulary = len(model.wv)

            embedding_rows = model.wv.vectors.shape[0]

            embedding_cols = model.wv.vectors.shape[1]

            ukuran_embedding = (
                f"{embedding_rows} × {embedding_cols}"
            )

            print(f"Vocabulary : {vocabulary}")
            print(f"Embedding  : {ukuran_embedding}")

            X = build_feature_matrix(
                model,
                tokens_col
            )

            print(
                f"VSM        : "
                f"{X.shape[0]} × {X.shape[1]}"
            )

            X_train, X_test, y_train, y_test = train_test_split(
                X,
                y,
                test_size=0.2,
                random_state=42,
                stratify=y
            )

            clf = GaussianNB()

            clf.fit(
                X_train,
                y_train
            )

            y_pred = clf.predict(
                X_test
            )

            acc = accuracy_score(
                y_test,
                y_pred
            )

            report = classification_report(
                y_test,
                y_pred,
                output_dict=True,
                zero_division=0
            )

            precision = report["weighted avg"]["precision"]

            recall = report["weighted avg"]["recall"]

            print(f"Akurasi    : {acc:.4f}")
            print(f"Precision  : {precision:.4f}")
            print(f"Recall     : {recall:.4f}")

            eksperimen_hasil.append({

                "skenario": nama_skenario,

                "window": window,

                "vector_size": vector_size,

                "vocabulary": vocabulary,

                "embedding_rows": embedding_rows,

                "embedding_cols": embedding_cols,

                "ukuran_embedding": ukuran_embedding,

                "vsm_rows": X.shape[0],

                "vsm_cols": X.shape[1],

                "akurasi": acc,

                "precision": precision,

                "recall": recall
            })

            if acc > best_accuracy:

                best_accuracy = acc

                best_skipgram = model

                best_clf = clf

                best_skenario = nama_skenario

                best_window = window

                best_vector_size = vector_size

                best_precision = precision

                best_recall = recall

                best_vocabulary = vocabulary

                best_embedding_rows = embedding_rows

                best_embedding_cols = embedding_cols

                best_vsm_rows = X.shape[0]

                best_vsm_cols = X.shape[1]


df_eksperimen = pd.DataFrame(
    eksperimen_hasil
)


df_eksperimen = (
    df_eksperimen
    .sort_values(
        "akurasi",
        ascending=False
    )
    .reset_index(drop=True)
)

print("\n")
print("=" * 110)
print("TABEL HASIL SELURUH EKSPERIMEN")
print("=" * 110)

display(
    df_eksperimen
)

print("\n")
print("=" * 80)
print("MODEL TERBAIK")
print("=" * 80)

print(f"Skenario       : {best_skenario}")

print(f"Stopword       : "
      f"{'DIHAPUS' if best_skenario == 'dengan_stopword_removal' else 'TIDAK DIHAPUS'}")

print(f"Window         : {best_window}")

print(f"Vector Size    : {best_vector_size}")

print(f"Vocabulary     : {best_vocabulary}")

print(
    f"Embedding      : "
    f"{best_embedding_rows} × {best_embedding_cols}"
)

print(
    f"VSM            : "
    f"{best_vsm_rows} × {best_vsm_cols}"
)

print(f"Akurasi        : {best_accuracy:.4f}")

print(f"Precision      : {best_precision:.4f}")

print(f"Recall         : {best_recall:.4f}")

print("\n")
print("=" * 80)
print("DETAIL MODEL TERBAIK")
print("=" * 80)

display(
    df_eksperimen.iloc[[0]]
)

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 100
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 100
VSM        : 200 × 100
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 99
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 99
VSM        : 200 × 99
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 98
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 98
VSM        : 200 × 98
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 97
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 97
VSM        : 200 × 97
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 96
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 96
VSM        : 200 × 96
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 95
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 95
VSM        : 200 × 95
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 94
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 94
VSM        : 200 × 94
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 93
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 93
VSM        : 200 × 93
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 92
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 92
VSM        : 200 × 92
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 91
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 91
VSM        : 200 × 91
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 90
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 90
VSM        : 200 × 90
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : tanpa_stopword_removal
Window      : 5
Vector Size : 89
======================================================================
Vocabulary : 5346
Embedding  : 5346 × 89
VSM        : 200 × 89
Akurasi    : 0.9500
Precision  : 0.9500
Recall     : 0.9500

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 100
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 100
VSM        : 200 × 100
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 99
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 99
VSM        : 200 × 99
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 98
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 98
VSM        : 200 × 98
Akurasi    : 1.0000
Precision  : 1.0000
Recall     : 1.0000

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 97
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 97
VSM        : 200 × 97
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 96
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 96
VSM        : 200 × 96
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 95
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 95
VSM        : 200 × 95
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 94
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 94
VSM        : 200 × 94
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 93
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 93
VSM        : 200 × 93
Akurasi    : 1.0000
Precision  : 1.0000
Recall     : 1.0000

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 92
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 92
VSM        : 200 × 92
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 91
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 91
VSM        : 200 × 91
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 90
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 90
VSM        : 200 × 90
Akurasi    : 0.9750
Precision  : 0.9762
Recall     : 0.9750

======================================================================
Skenario    : dengan_stopword_removal
Window      : 5
Vector Size : 89
======================================================================
Vocabulary : 5299
Embedding  : 5299 × 89
VSM        : 200 × 89
Akurasi    : 1.0000
Precision  : 1.0000
Recall     : 1.0000


==============================================================================================================
TABEL HASIL SELURUH EKSPERIMEN
==============================================================================================================

,skenario,window,vector_size,vocabulary,embedding_rows,embedding_cols,ukuran_embedding,vsm_rows,vsm_cols,akurasi,precision,recall
0,dengan_stopword_removal,5,93,5299,5299,93,5299 × 93,200,93,1.000,1.00000,1.000
1,dengan_stopword_removal,5,89,5299,5299,89,5299 × 89,200,89,1.000,1.00000,1.000
2,dengan_stopword_removal,5,98,5299,5299,98,5299 × 98,200,98,1.000,1.00000,1.000
3,tanpa_stopword_removal,5,100,5346,5346,100,5346 × 100,200,100,0.975,0.97619,0.975
4,tanpa_stopword_removal,5,96,5346,5346,96,5346 × 96,200,96,0.975,0.97619,0.975
5,tanpa_stopword_removal,5,99,5346,5346,99,5346 × 99,200,99,0.975,0.97619,0.975
6,tanpa_stopword_removal,5,98,5346,5346,98,5346 × 98,200,98,0.975,0.97619,0.975
7,tanpa_stopword_removal,5,97,5346,5346,97,5346 × 97,200,97,0.975,0.97619,0.975
8,tanpa_stopword_removal,5,93,5346,5346,93,5346 × 93,200,93,0.975,0.97619,0.975
9,tanpa_stopword_removal,5,94,5346,5346,94,5346 × 94,200,94,0.975,0.97619,0.975
10,tanpa_stopword_removal,5,95,5346,5346,95,5346 × 95,200,95,0.975,0.97619,0.975
11,tanpa_stopword_removal,5,92,5346,5346,92,5346 × 92,200,92,0.975,0.97619,0.975
12,dengan_stopword_removal,5,99,5299,5299,99,5299 × 99,200,99,0.975,0.97619,0.975
13,dengan_stopword_removal,5,100,5299,5299,100,5299 × 100,200,100,0.975,0.97619,0.975
14,tanpa_stopword_removal,5,90,5346,5346,90,5346 × 90,200,90,0.975,0.97619,0.975
15,tanpa_stopword_removal,5,91,5346,5346,91,5346 × 91,200,91,0.975,0.97619,0.975
16,dengan_stopword_removal,5,94,5299,5299,94,5299 × 94,200,94,0.975,0.97619,0.975
17,dengan_stopword_removal,5,97,5299,5299,97,5299 × 97,200,97,0.975,0.97619,0.975
18,dengan_stopword_removal,5,95,5299,5299,95,5299 × 95,200,95,0.975,0.97619,0.975
19,dengan_stopword_removal,5,96,5299,5299,96,5299 × 96,200,96,0.975,0.97619,0.975
20,dengan_stopword_removal,5,91,5299,5299,91,5299 × 91,200,91,0.975,0.97619,0.975
21,dengan_stopword_removal,5,92,5299,5299,92,5299 × 92,200,92,0.975,0.97619,0.975
22,dengan_stopword_removal,5,90,5299,5299,90,5299 × 90,200,90,0.975,0.97619,0.975
23,tanpa_stopword_removal,5,89,5346,5346,89,5346 × 89,200,89,0.950,0.95000,0.950

================================================================================
MODEL TERBAIK
================================================================================
Skenario       : dengan_stopword_removal
Stopword       : DIHAPUS
Window         : 5
Vector Size    : 98
Vocabulary     : 5299
Embedding      : 5299 × 98
VSM            : 200 × 98
Akurasi        : 1.0000
Precision      : 1.0000
Recall         : 1.0000


================================================================================
DETAIL MODEL TERBAIK
================================================================================

,skenario,window,vector_size,vocabulary,embedding_rows,embedding_cols,ukuran_embedding,vsm_rows,vsm_cols,akurasi,precision,recall
0,dengan_stopword_removal,5,93,5299,5299,93,5299 × 93,200,93,1.0,1.0,1.0

## Menyimpan Model Terbaik

In [ ]:
import os
import json
import joblib


os.makedirs(
    "model_streamlit",
    exist_ok=True
)

best_skipgram.save(
    "model_streamlit/best_skipgram.model"
)

joblib.dump(
    best_clf,
    "model_streamlit/best_naive_bayes.joblib"
)

pakai_stopword_removal = (
    best_skenario == "dengan_stopword_removal"
)

metadata = {

    "skenario": best_skenario,

    "stopword_removal": pakai_stopword_removal,

    "window": best_window,

    "vector_size": best_vector_size,

    "akurasi": float(best_accuracy),

    "precision": float(best_precision),

    "recall": float(best_recall),

    "vocabulary": int(best_vocabulary),

    "embedding_rows": int(best_embedding_rows),

    "embedding_cols": int(best_embedding_cols),

    "ukuran_embedding": (
        f"{best_embedding_rows} × "
        f"{best_embedding_cols}"
    ),

    "vsm_rows": int(best_vsm_rows),

    "vsm_cols": int(best_vsm_cols),

    "model_embedding": "Word2Vec Skip-gram",

    "model_classifier": "GaussianNB"
}

with open(
    "model_streamlit/metadata.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

print("\n")
print("=" * 80)
print("MODEL TERBAIK BERHASIL DISIMPAN")
print("=" * 80)

print(f"Skenario       : {best_skenario}")

print(
    f"Stopword       : "
    f"{'DIHAPUS' if pakai_stopword_removal else 'TIDAK DIHAPUS'}"
)

print(f"Window         : {best_window}")

print(f"Vector Size    : {best_vector_size}")

print(f"Vocabulary     : {best_vocabulary}")

print(
    f"Embedding      : "
    f"{best_embedding_rows} × {best_embedding_cols}"
)

print(
    f"VSM            : "
    f"{best_vsm_rows} × {best_vsm_cols}"
)

print(f"Akurasi        : {best_accuracy:.4f}")

print(f"Precision      : {best_precision:.4f}")

print(f"Recall         : {best_recall:.4f}")

print("\nFile yang disimpan:")

print(
    "1. model_streamlit/best_skipgram.model"
)

print(
    "2. model_streamlit/best_naive_bayes.joblib"
)

print(
    "3. model_streamlit/metadata.json"
)

print("\nModel terbaik siap digunakan untuk Streamlit.")

================================================================================
MODEL TERBAIK BERHASIL DISIMPAN
================================================================================
Skenario       : dengan_stopword_removal
Stopword       : DIHAPUS
Window         : 5
Vector Size    : 98
Vocabulary     : 5299
Embedding      : 5299 × 98
VSM            : 200 × 98
Akurasi        : 1.0000
Precision      : 1.0000
Recall         : 1.0000

File yang disimpan:
1. model_streamlit/best_skipgram.model
2. model_streamlit/best_naive_bayes.joblib
3. model_streamlit/metadata.json

Model terbaik siap digunakan untuk Streamlit.